<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>my_cartographer</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="a202@todo.todo">a202</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <exec_depend>cartographer_ros</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  
  <!-- TF -->
  <exec_depend>tf2_ros</exec_depend>

  <!-- LiDAR Driver -->
  <exec_depend>ydlidar_ros2_driver</exec_depend>

  <!-- IMU Driver -->
  <exec_depend>mpu6050driver</exec_depend>

  <!-- RViz -->
  <exec_depend>rviz2</exec_depend>

  <!-- rclcpp/rclpy (Node 실행) -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclpy</exec_depend>


  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
